### ISSUE TITLE
Do not show gallery if it empty

### ISSUE THREAD

**Issue by karmelalla** [karmelalla/karmelalla.github.io#72]
![image](https://user-images.githubusercontent.com/25576796/31928253-4bf0a878-b84c-11e7-9f3c-f870d6f6895e.png)

**Comment by kisakov** [comment]
There were empty images key https://github.com/karmelalla/karmelalla.github.io/commit/9bad65d1ed4cbb85c662acdd06f4a3f3d47ed668#diff-b353e771314e99059bd70d46ba9d16e8L8
